src/assn2proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

src/blog/urls.py
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('init', views.init, name='init'),
    path('blogHome', views.blogHome, name='blogHome'),
    path('blogArchive', views.blogArchive, name='blogArchive'),
    path('aboutMe', views.aboutMe, name='aboutMe'),
    path('techTips', views.techTips, name='techTips'),
    path('blog/<int:blog_id>/', views.viewBlog, name='blog'),
    path('<int:blog_id>/comment/', views.comment, name='comment'),
]

src/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	title=models.CharField(max_length = 200)
	author=models.CharField(max_length = 200)
	content=models.TextField(max_length = 100000)
	posted_date = models.DateTimeField('date posted')
	def numComments(self):
		return Comment.objects.filter(blog = self).count()
	comments = property(numComments)
	
class Comment(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	title=models.CharField(max_length = 200)
	author=models.CharField(max_length = 200)
	content=models.TextField(max_length = 10000)
	posted_date = models.DateTimeField('date posted')
	email = models.EmailField(max_length=254, default="example@example.com")

src/blog/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from time import strftime
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from .models import Blog, Comment
from django.urls import reverse
import random as rand;

generated_content = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sed neque aliquam, viverra est eget, rhoncus urna. Cras vel lacinia nulla. Curabitur quis ornare sem. Maecenas posuere rhoncus elit ac ultricies. Maecenas sodales, libero ut interdum ultrices, turpis libero maximus justo, et ultricies ante arcu at nibh. Nullam vehicula, eros eget dictum posuere, nunc nisl pharetra est, non dignissim libero nunc a nibh. Nullam cursus cursus dolor eget bibendum. Suspendisse ac sollicitudin dolor, sit amet ullamcorper neque. Phasellus fermentum nisl a nibh consequat, quis porttitor justo efficitur.

Curabitur accumsan tortor quis luctus fermentum. Aenean neque ipsum, consectetur vel dapibus sed, molestie quis risus. Ut ac ultricies risus. Ut imperdiet, dui eu feugiat tincidunt, ex tortor placerat diam, eget pellentesque mi tortor in sem. Maecenas tristique venenatis eros, vitae rutrum nisl molestie nec. Nulla laoreet ornare justo sit amet maximus. Donec efficitur turpis vitae ex cursus tincidunt. Sed ut neque ut velit ultricies rutrum nec sit amet erat. Aliquam fermentum in metus vel mollis. Mauris ligula massa, lacinia id vulputate sit amet, congue at nulla. Ut efficitur porttitor sollicitudin.

Etiam in feugiat dolor, nec feugiat augue. Nulla sit amet augue urna. Suspendisse porttitor dolor a ligula mollis bibendum venenatis eget nisi. Praesent blandit et ex sed convallis. Maecenas malesuada tempor tellus nec laoreet. Vestibulum fermentum sodales mauris in dictum. Cras fermentum gravida sapien nec finibus. Morbi eget sollicitudin nunc. Ut dapibus cursus interdum. Vivamus aliquet vestibulum nibh, id tempor sem scelerisque ac. Phasellus et pulvinar quam. Vivamus nec convallis orci. Morbi lectus augue, hendrerit laoreet erat ut, fringilla sollicitudin ante. In tempus tincidunt volutpat. Vivamus lectus leo, sodales nec lacinia eu, vulputate a arcu.

Quisque porttitor suscipit finibus. Aenean at condimentum augue. Nulla varius metus a tortor euismod laoreet. Etiam quis nisi ante. Praesent imperdiet, ipsum id euismod efficitur, purus ante luctus leo, ut vestibulum sem justo mattis diam. Donec aliquet porttitor lectus, vel fermentum augue. Morbi ultrices metus lectus, et lobortis mi auctor in. Suspendisse scelerisque dui quis elit sagittis condimentum. Nam tincidunt odio in orci posuere auctor ac cursus odio. Morbi dapibus, quam sed placerat congue, justo ex cursus mi, vel euismod sapien metus vel lectus. Pellentesque tristique nulla ut ullamcorper suscipit. Nulla tellus mi, imperdiet a orci ac, finibus varius orci. Donec sit amet interdum nulla. Sed luctus aliquam arcu sed maximus. Nunc ut vestibulum enim. Nullam tempor magna at suscipit sollicitudin.

Vivamus luctus mauris at risus pellentesque ornare. Donec aliquet consequat lacus, eget vestibulum dui cursus et. Mauris eleifend, velit nec cursus ultrices, eros erat aliquam tortor, eu vulputate sapien metus viverra orci. Pellentesque pharetra felis est, eu tempor arcu convallis ac. Donec ac sodales purus. Donec euismod ex ante, eu lobortis libero sodales sed. In hac habitasse platea dictumst.

'''

generated_comment = '''
This is a generated comment. Yay!
'''


def nuke(request):
    for b in Blog.objects.all():
        b.delete()
    for c in Comment.objects.all():
        c.delete()
    return HttpResponseRedirect(reverse('blog:index'))


def index(request):
    now = strftime('%c')
    return render(request, 'blog/index.html', {
        'now': now
    })


def init(request):
	nuke(request)
	for i in range(10):
            blog = Blog(title="Title" + str(i), content=generated_content,
                        author="Someone important", posted_date=datetime.datetime.now())
            blog.save()
            for j in range(i):
                comment = Comment(title="title" + str(rand.randint(0,100)), author = "jd03", blog = blog, content = generated_comment, posted_date = datetime.datetime.now(), email = "example@example.com")
                comment.save()
	return HttpResponseRedirect(reverse('blog:blogHome'))


def blogHome(request):
    now = strftime('%c')
    blogs = Blog.objects.order_by('-posted_date')[:3]
    return render(request, 'blog/blog_home.html', {
        'now': now,
        'blogs': blogs,
    })

def blogArchive(request):
    blogs = Blog.objects.order_by('-posted_date')
    return render(request, 'blog/blog_archive.html', {
        'blogs': blogs,
    })


def aboutMe(request):
    now = strftime('%c')
    return render(request, 'blog/about_me.html', {
        'now': now
    })


def techTips(request):
    now = strftime('%c')
    return render(request, 'blog/tech_tips.html', {
        'now': now
    })


def viewBlog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/blog_view.html', {
        'blog': blog,
        'comments':Comment.objects.filter(blog=blog).order_by('-posted_date'),
    })
    #adsf

def comment(request, blog_id):
    postData = request.POST
    comment = Comment(title=postData['title'], author=postData['author'], email=postData['email'], content=postData['content'], posted_date = datetime.datetime.now(), blog=Blog.objects.get(pk=blog_id))
    comment.save()
    return HttpResponseRedirect(reverse('blog:blog', args=[blog_id]))

src/blog/templates/blog/about_me.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}
{% static "blog/profile_75.jpg" as profile %}
{% static "blog/climbing.jpg" as climbing %}

<!DOCTYPE html>
<!--Welcome to my code.-->
<html lang="en">
	<head>
		<title>About Me</title>
		<meta charset="utf-8"/>
		<link rel="stylesheet" href="{{styles}}"/>
	</head>
	<body>
		<div>
			<h1>Welcome!</h1>
			<h2>Thank you for checking out my resume.</h2>
			<h3>Right now it is {{now}}.</h3>
			<p id="little"><a href=".">&lt;-- Back</a></p>
			<img height="153" width="230" alt="profile" src="{{profile}}" />
			<p class="bio">
				Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
			</p>
			<div class="column">
				<div class="super-item work">
					<h3>Relevant Work Experience</h3>
					<div class="sub-item">
						<h4>QA and Development Intern</h4>
						<div class="info">
							ContractPal | Lindon, UT<br/>
							October 2017 - Present
						</div>
						<div class="data">
							My primary responsibilities include:
							<ul>
								<li>Manually test web applications to find bugs before clients and customers</li>
								<li>Design and write automation scripts for regression testing</li>
								<li>Determine customer priorities and requirements, then deliver them to the developer for development</li>
								<li>Make minor UI and workflow changes</li>
								<li>Manage datasets</li>
								<li>Reproduce and isolate bugs so the developer can easily pinpoint how to fix them</li>
							</ul>
						</div>
					</div>
					<div class="sub-item">
						<h4>QA Intern</h4>
						<div class="info">
							ContractPal | Lindon, UT<br/>
							Aug 2013 - Oct 2015
						</div>
						<div class="data">
							Learned basic HTML/CSS/JavaScript in a model-view-controller framework. Wrote unit tests for and web applications on a Java based JS-syntax platform.
						</div>
					</div>
					<h3>Unrelated Work Experience</h3>
					<div class="sub-item">
						<h4>Piano Teacher</h4>
						<div class="info">
							Self-employed | Spanish Fork, UT<br/>
							2012-2014
						</div>
					</div>
				</div>
			</div>
			<div class="column">
				<div class="super-item education">
					<h3>Education</h3>
					<div class="sub-item">
						<h4><a href="https://www.usu.edu" target="_blank">Utah State University</a></h4>
						<div class="info">
							Computer Science<br/>
							2014 - 2015, 2017 - Present
						</div>
						<div class="data">
							Classes of interest:
							<br/>
							<ul>
								<li>CS1400 - CS1</li>
								<li>CS1410 - CS2</li>
								<li>CS1440 - Methods in CS</li>
								<li>CS2410 - Intro to Event Driven Programming and GUIs</li>
								<li>CS2420 - Algorithms and Data Structures</li>
								<li>CS2810 - Computer Systems Organization and Architecture</li>
								<li>ITLS5265 - Internet Development</li>
								<li>MATH1220 - Calculus II</li>
								<li>MATH2270 - Linear Algebra</li>
								<li>MATH3310 - Discrete Math</li>
							</ul>
							Cumulative GPA: 3.85
						</div>
					</div>
				</div>
				<div class="super-item skills">
					<h3>Technical Skills</h3>
					<div class="sub-item">
						<ul>
							<li>Proficient in Java</li>
							<li>Basic to Intermediate HTML/CSS/JavaScript</li>
							<li>Basic Python</li>
							<li>Beginner XPath, SQL</li>
						</ul>
					</div>
					<h3>Personal Skills</h3>
					<div class="sub-item">
						<h4>Communication</h4>
						<h4>Self-Motivation</h4>
					</div>
				</div>
			</div>
			<div>
				<p>I also like climbing! <br/>
				<img width="240" height="240" alt="climbing" src="{{climbing}}"/>
			</div>
		</div>
	</body>
	<!--this is another comment-->
</html>

src/blog/templates/blog/blog_archive.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="utf-8" />
    <title>Blog Archive</title>
    <link rel="stylesheet" href="{{styles}}" />
</head>

<body>
    <div>
        <h2>Blog Archive</h2>
        <p><a href="blogHome">Blog Home</a></p>
        {% for blog in blogs %}
        <div class="blog">
            <h2><a href="blog/{{blog.id}}/">{{blog.title}}</a></h2>
            <h3>By {{blog.author}}</h3>
            <p>{{blog.content | truncatewords:200 }}</p>
            <p class="info">{{blog.posted_date}}</p>
            <p>{{blog.comments}} Comments</p>
        </div>
        {% endfor %}
    </div>
</body>

</html>

src/blog/templates/blog/blog_home.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}

<!DOCTYPE html>
<!--Welcome to my code.-->
<html lang="zxx">

<head>
    <meta charset="utf-8" />
    <title>Blog Home</title>
    <link rel="stylesheet" href="{{styles}}" />
</head>

<body>
    <div>
        <h2>Blog Home</h2>
        <p><a href="blogArchive">Blog Archive</a></p>
        <p><a href=".">Index</a></p>
        {% for blog in blogs %}
        <div class="blog">
            <h2><a href="blog/{{blog.id}}/">{{blog.title}}</a></h2>
            <h3>By {{blog.author}}</h3>
            <p>{{blog.content | truncatewords:200 }}</p>
            <p class="info">{{blog.posted_date}}</p>
            <p>{{blog.comments}} Comments</p>
        </div>
        {% endfor %}
    </div>
</body>
<!--this is another comment-->

</html>

src/blog/templates/blog/blog_view.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="utf-8" />
	<title>Seth's resume</title>
	<link rel="stylesheet" href="{{styles}}" />
</head>

<body>
	<div>
		<a href="../../blogHome">&lt;-- Back</a>
		<h1>{{blog.title}}</h1>
		<h2>By {{blog.author}}</h2>
		<p>{{blog.content}}</p>
		<p class="info">{{blog.posted_date}}</p>
	</div>
	<div>
		<form action="{% url 'blog:comment' blog.id %}" method="post">
			<label for="title">Title: </label><input type="text" name="title" id="title" maxlength="200"/><br/>
			<label for="email">Email: </label><input type="email" name="email" id="email"/><br/>
			<label for="author">Nickname: </label><input type="text" name="author" id="author" maxlength="200"/><br/>
			<textarea name="content" maxlength="10000"></textarea><br/>
			<input type="submit" value="Comment" />
			{% csrf_token %}
		</form>
	</div>

	<div>
		{% for comment in comments %}
		<div class="comment">
			<h4>{{comment.title}}</h4>
			<p><i>By {{comment.author}}</i><span class="right">, {{comment.posted_date}}</span></p>
			<p>{{comment.content}}</p>
		</div>
		{% endfor %}
	</div>
</body>

</html>

src/blog/templates/blog/index.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}

<!DOCTYPE html>
<!--Welcome to my code.-->
<html lang="zxx">
		<head>
			<meta charset="utf-8"/>
		<title>Seth's resume</title>
		<link rel="stylesheet" href="{{styles}}"/>
	</head>
	<body>
		<div>
			<h1>Welcome!</h1>
			<h2>Thank you for checking out my website.</h2>
			<h3>Right now it is {{now}}.</h3>
			<ol>
			<li><a href="aboutMe">My Resume (a bit about me)</a></li>
			<li><a href="techTips">Tech Tips (you probably know more though)</a></li>
			<li><a href="blogHome">Blog home</a></li>
			<li><a href="blogArchive">Blog archive</a></li>
			<li><a href="blogArchive">Nuke and pave</a></li>
			</ol>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<p>
				Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
			</p>
			<p>
			At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
			</p>
		</div>
	</body>
	<!--this is another comment-->
</html>

src/blog/templates/blog/tech_tips.html
{% load static from staticfiles %}
{% static "blog/styles.css" as styles %}

<!DOCTYPE html>
<!--Welcome to my code.-->
<html lang="en">
	<head>
		<title>Tech Tips</title>
		<link rel="stylesheet" href="{{styles}}"/>
			<meta charset="utf-8"/>
	</head>
	<body>
		<div>
			<h2>Thank you for checking out my tech tips.</h2>
			<h3>Right now it is {{now}}.</h3>
			<p id="little"><a href=".">&lt;-- Back</a></p>
			
			<table>
				<thead>
					<tr>
						<td>Command name</td>
						<td>Description</td>
						<td>Example</td>
					</tr>
					<tr>
						<td>commit</td>
						<td>Writes changes to the repo.</td>
						<td><code>git commit -m "This is my first commit"</code></td>
					</tr>
				</thead>
			</table>
		</div>
	</body>
	<!--this is another comment-->
</html>